name: Pytest Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download the repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install the package
        run: pip install .
      
      - name: Run the tests
        run: pytest
